version: "3.7"

services:

  caddy:
    image: lucaslorentz/caddy-docker-proxy:0.3-alpine
    ports:
      - 80:80
      - 443:443
      - 2015:2015
    networks:
      - caddy
    command: -email youremail@test.com -agree=true -log stdout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy-data:/etc/.caddy

  quick-mate:
    build: .
    image: flaviostutz/quick-mate
    environment:
      - STUN_HOST_PORT=coturn_host:3478
      - TURN_HOST_PORT=coturn_host:3478
      - TURN_USERNAME=coturn
      - TURN_CREDENTIAL=oursecret
    networks:
      - caddy
    labels:
      caddy.address: test.com
      caddy.targetport: "8080"

  coturn:
    image: flaviostutz/coturn:4.5.0.4
    network_mode: host
    environment:
      - TURN_USERNAME=coturn
      - TURN_PASSWORD=oursecret

networks:
  caddy:
    driver: bridge

volumes:
    caddy-data:


