version: "3"

services:

  nginx-cache-proxy:
    image: flaviostutz/nginx-cache-proxy:1.9.1
    ports:
      - 8383:80
      - 8443:443
    environment:
      - PROXY_PASS_URL=http://quick-mate:8080/
      - SSL_DOMAIN=localhost
      # - REQUEST_LOG_LEVEL=body

  quick-mate:
    build: .
    image: flaviostutz/quick-mate
    ports:
      - 8484:8080
    # volumes:
    #   - /Users/flaviostutz/Documents/development/flaviostutz/quick-mate/server-quick-mate/static:/app/easyrtc/server-quick-mate/static
